
from manim import *

class AutoGeneratedScene(Scene):
    def construct(self):
        title = Text("Newton's Laws of Motion", font_size=32).move_to(UP * 2)
        self.play(FadeIn(title))
        self.wait(2)
        self.play(FadeOut(title))

        # Explanation steps or direct text
        steps = ["1. Newton's First Law (Law of Inertia): An object at rest stays at rest, and an object in motion stays in motion at a constant velocity, unless acted on by an external force.\n2. Newton's Second Law (Law of Acceleration): The force acting on an object is equal to the mass of the object times its acceleration (F=ma).\n3. Newton's Third Law (Law of Action-Reaction): For every action, there is an equal and opposite reaction."]
        text_objects = VGroup()  # Grouping for proper alignment

        for step in steps:
            step_text = Paragraph(
                step,
                font_size=76, 
                line_spacing=1.4,
                alignment="center"
            ).scale(0.9)

            step_text.set_width(config.frame_width * 0.85)  # Ensures margin from edges
            step_text.move_to(ORIGIN)  # Centers text perfectly

            text_objects.add(step_text)

            self.play(Write(step_text))
            self.wait(4)  # Extended wait time for readability
            self.play(FadeOut(step_text))
            self.wait(1)

        # Thank you message
        thank_you = Text("Thank you", font_size=30).move_to(DOWN * 2)
        self.play(FadeIn(thank_you))
        self.wait(2)
        self.play(FadeOut(thank_you))
